// Generates assets/css/lucide.css – mask-based icon classes for every Lucide icon referenced in the theme.
// (The React site uses lucide-react; this reproduces the exact outline glyphs inside Elementor Icon / Icon List widgets.)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const theme = path.join(root, 'trinity-media-theme');
const iconDir = path.join(root, 'artifacts/trinity-media/node_modules/lucide-react/dist/esm/icons');

function walk(dir, out = []) {
  for (const f of fs.readdirSync(dir, { withFileTypes: true })) {
    if (f.name === 'images' || f.name === 'node_modules') continue;
    const p = path.join(dir, f.name);
    if (f.isDirectory()) walk(p, out);
    else if (/\.(php|json|js|css)$/.test(f.name) && f.name !== 'lucide.css') out.push(p);
  }
  return out;
}

const pascal = (k) => k.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join('');
function aliasIndex() {
  const idx = {};
  const src = fs.readFileSync(path.join(iconDir, '..', 'lucide-react.js'), 'utf8');
  for (const m of src.matchAll(/export \{([^}]+)\} from '\.\/icons\/([a-z0-9-]+)\.js'/g)) {
    for (const n of m[1].split(',')) { const mm = n.trim().match(/default as (\w+)/); if (mm) idx[mm[1]] = m[2]; }
  }
  return idx;
}

export function buildLucide() {
  const alias = aliasIndex();
  const used = new Set();
  const extra = [path.join(root, 'wp-build/css'), path.join(root, 'wp-build/js')];
  for (const f of [...walk(theme), ...extra.flatMap((d) => walk(d))]) {
    const s = fs.readFileSync(f, 'utf8');
    for (const m of s.matchAll(/tm-lucide-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) used.add(m[1]);
    for (const m of s.matchAll(/--tm-ic-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) used.add(m[1]);
    // trinity_icon( 'name' ) in PHP
    for (const m of s.matchAll(/trinity_icon\(\s*'([a-z0-9-]+)'/g)) used.add(m[1]);
    for (const m of s.matchAll(/'icon'\s*=>\s*'([a-z0-9-]+)'/g)) used.add(m[1]);
  }
  used.delete('');
  const rules = [];
  const vars = [];
  const missing = [];
  for (const name of [...used].sort()) {
    const real = alias[pascal(name)] || name;
    const file = path.join(iconDir, `${real}.js`);
    if (!fs.existsSync(file)) { missing.push(name); continue; }
    const src = fs.readFileSync(file, 'utf8');
    const m = src.match(/createLucideIcon\("[^"]+",\s*(\[[\s\S]*?\])\);/);
    if (!m) { missing.push(name); continue; }
    // eslint-disable-next-line no-eval
    const nodes = eval(m[1]);
    const inner = nodes.map(([tag, attrs]) => {
      const a = Object.entries(attrs).filter(([k]) => k !== 'key').map(([k, v]) => `${k}="${v}"`).join(' ');
      return `<${tag} ${a}/>`;
    }).join('');
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`;
    const uri = 'data:image/svg+xml,' + encodeURIComponent(svg).replace(/'/g, '%27').replace(/"/g, '%22');
    vars.push(`--tm-ic-${name}:url("${uri}")`);
    rules.push(`.tm-lucide-${name}{--tm-i:var(--tm-ic-${name})}`);
  }
  const css = `/* Generated by wp-build/lucide.mjs – Lucide outline icons as CSS masks (colour = currentColor). */
.tm-lucide{display:inline-block;flex:none;width:1em;height:1em;vertical-align:-0.125em;background-color:currentColor;-webkit-mask:var(--tm-i) center/contain no-repeat;mask:var(--tm-i) center/contain no-repeat;font-style:normal}
.elementor-widget-icon .elementor-icon i.tm-lucide,.elementor-widget-icon-list i.tm-lucide{display:block;width:1em;height:1em}
.elementor-icon-list-icon i.tm-lucide{width:1em;height:1em}
:root{${vars.join(';')}}
${rules.join('\n')}
`;
  fs.writeFileSync(path.join(theme, 'assets/css/lucide.css'), css);
  return { count: rules.length, missing };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) console.log(buildLucide());
